### PR TITLE
Updates August 15 2023

### PR DESCRIPTION
**Pull request by vcojocaru**

### CODE REVIEW

**Review by rvhonorato — COMMENTED** [review]
no idea about these updates, did you confirm the site is building?

**Comment by vcojocaru** [comment]
> no idea about these updates, did you confirm the site is building?

these are updates of all packages used just like those I did in June to solve the security issues at that time. and yes, the site is building

**Comment by rvhonorato** [comment]
"Updates August 15 2023" does not mean anything, also there is no description about what was changed so there's absolutely no way for me to check this

**Comment by vcojocaru** [comment]
Okay, I forced the merge without a review. Files Changed under the PR menu tells what has been changed (minor changes). Like after the larger set of updates in June that you approved, the page is building. I guess that is the only test needed.

**Pull request merged**
